[common]
bind_addr = "0.0.0.0"
bind_port = 7000
dashboard_port = 7500
dashboard_user = "admin"
dashboard_pwd = "admin"
token = "12345qwert"
log_level = "info"
log_file_enabled = false
log_max_days = 30
disable_log_color = true
autostart = false
log_file = ""
